AWSTemplateFormatVersion: 2010-09-09
Description: VPCEndpoint Template for CloudFormation Demo. Depends on cfn-vpc.yaml, cfn-sg.yaml.
#Metadata: 

Parameters: 
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo 
  
#Mappings: 

#Conditions: 

Resources:
# VPC Endpoint for S3
  S3VPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:      
      VpcEndpointType: Gateway
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcId: 
        Fn::ImportValue: !Sub ${StackPrefix}-VPC-ID
      RouteTableIds:
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateRouteTableId

# VPC Endpoint for CloudWatch Logs
  CloudWatchLogsVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:      
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.logs
      SubnetIds:
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetOneId
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetTwoId
      VpcId: 
        Fn::ImportValue: !Sub ${StackPrefix}-VPC-ID          
      SecurityGroupIds: 
        - Fn::ImportValue: !Sub ${StackPrefix}-VPCEndpointSecurityGroup-ID                      
      PrivateDnsEnabled: true

# ECR VPC Endpoint
  ECRApiVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:      
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.api
      SubnetIds:
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetOneId
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetTwoId
      VpcId: 
        Fn::ImportValue: !Sub ${StackPrefix}-VPC-ID          
      SecurityGroupIds: 
        - Fn::ImportValue: !Sub ${StackPrefix}-VPCEndpointSecurityGroup-ID        
      PrivateDnsEnabled: true

  ECRDkrVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:      
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.dkr
      SubnetIds:
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetOneId
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetTwoId
      VpcId: 
        Fn::ImportValue: !Sub ${StackPrefix}-VPC-ID          
      SecurityGroupIds: 
        - Fn::ImportValue: !Sub ${StackPrefix}-VPCEndpointSecurityGroup-ID
      PrivateDnsEnabled: true

#Outputs: